#!/bin/bash
git init -qqq
git remote add origin https://github.com/jblackburn-incomm/docker-magento
git fetch origin -qqq
git checkout origin/Change_Local_Port -- compose
mv compose/* ./
mv compose/.gitignore ./
mv compose/.vscode ./
rm -rf compose .git
git init
